# Generated by Django 5.0.3 on 2024-03-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(default='', upload_to='media/product')),
                ('title', models.CharField(default='', max_length=100)),
                ('desc', models.TextField(default='', max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
