# Generated by Django 5.0.3 on 2024-03-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='image',
            field=models.FileField(default='', upload_to='media/activites'),
        ),
    ]
