# Generated by Django 5.0.3 on 2024-03-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watad', '0002_alter_activities_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='partners',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(default='', upload_to='media/partners')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
