# Generated by Django 5.0.2 on 2024-04-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watad', '0004_activity_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='details_job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('desc', models.TextField(default='', max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
