# Generated by Django 5.0.2 on 2024-04-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watad', '0006_details_job_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='calls',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField()),
                ('exp_date', models.DateTimeField()),
                ('email', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=200)),
                ('mobile', models.CharField(default='', max_length=200)),
                ('subject', models.TextField(default='', max_length=100)),
            ],
        ),
    ]
